package com.hushkisses.spacesurvival.role;

public enum RoleCapability {
    DIAGNOSE_FAULT,
    ADVANCED_REPAIR,
    REDISTRIBUTE_POWER,

    PRECISE_INFECTION_TEST,
    ADVANCED_TREATMENT,
    SUPPRESS_INFECTION,

    EXECUTE_DISARM,
    EXECUTE_DETENTION,
    USE_SECURITY_SYSTEM,
    EMERGENCY_LIMITED_PVP,

    PRECISE_BIO_ANALYSIS,
    RESEARCH_ALIEN_LIFE,
    IDENTIFY_EVENT_CAUSE,

    PRECISE_NAVIGATION_DATA,
    CHANGE_DESTINATION,
    LONG_RANGE_COMMUNICATION,
    DISTRESS_SIGNAL,

    PRECISE_INVENTORY_CHECK,
    IDENTIFY_RARE_RESOURCE,
    HIGH_EFFICIENCY_PROCESSING
}
