name: SpaceSurvival
version: '${version}'
main: com.hushkisses.spacesurvival.paper.SpaceSurvivalPlugin
description: Minecraft space social survival game
author: Hushkisses
api-version: '26.2'
softdepend: [ItemsAdder, voicechat, MythicMobs, ModelEngine]

commands:
  space:
    description: 우주 생존게임 명령어
    usage: /space status
    permission: spacesurvival.use

permissions:
  spacesurvival.use:
    description: 우주 생존게임 기본 명령어 사용 권한
    default: true
  spacesurvival.admin:
    description: 우주 생존게임 관리 명령어 사용 권한
    default: op
