info:
  namespace: spacesurvival

items:
  repair_parts:
    name: "수리 부품"
    material: IRON_NUGGET
    graphics:
      texture: item/repair_parts

  circuits:
    name: "회로판"
    material: REDSTONE
    graphics:
      texture: item/circuits

  power_cells:
    name: "전력 셀"
    material: GLOWSTONE_DUST
    graphics:
      texture: item/power_cells

  fuel:
    name: "연료"
    material: BLAZE_POWDER
    graphics:
      texture: item/fuel

  medical_supplies:
    name: "의료 물자"
    material: PAPER
    graphics:
      texture: item/medical_supplies

  bio_samples:
    name: "생체 샘플"
    material: SLIME_BALL
    graphics:
      texture: item/bio_samples

  data_cores:
    name: "데이터 코어"
    material: AMETHYST_SHARD
    graphics:
      texture: item/data_cores

  engineering_multitool:
    name: "엔지니어 멀티툴"
    material: IRON_PICKAXE
    graphics:
      texture: item/engineering_multitool

  medical_scanner:
    name: "의료 스캐너"
    material: PAPER
    graphics:
      texture: item/medical_scanner

  security_keycard:
    name: "보안 키카드"
    material: TRIPWIRE_HOOK
    graphics:
      texture: item/security_keycard

  research_scanner:
    name: "연구 스캐너"
    material: PAPER
    graphics:
      texture: item/research_scanner

  radio:
    name: "장거리 무전기"
    material: PAPER
    graphics:
      texture: item/radio

  cargo_scanner:
    name: "화물 스캐너"
    material: PAPER
    graphics:
      texture: item/cargo_scanner

  hull_breach:
    name: "선체 균열"
    material: CRACKED_STONE_BRICKS
    graphics:
      texture: item/hull_breach


  map_hotspot:
    name: "지도 핫스팟"
    material: PAPER
    graphics:
      texture: item/map_hotspot

  map_current_marker:
    name: "현재 위치"
    material: PAPER
    graphics:
      texture: item/map_current_marker

  map_target_marker:
    name: "긴급 목표"
    material: PAPER
    graphics:
      texture: item/map_target_marker

  map_current_target_marker:
    name: "현재 위치 / 긴급 목표"
    material: PAPER
    graphics:
      texture: item/map_current_target_marker

  map_optional_marker:
    name: "보조 구역"
    material: PAPER
    graphics:
      texture: item/map_optional_marker

  map_info_button:
    name: "지도 정보"
    material: PAPER
    graphics:
      texture: item/map_info_button

  map_route_button:
    name: "추천 경로"
    material: PAPER
    graphics:
      texture: item/map_route_button

  map_back_button:
    name: "돌아가기"
    material: PAPER
    graphics:
      texture: item/map_back_button
